# Generated by Django 5.0.2 on 2024-05-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokolova', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
